"""add_listing_type

Revision ID: ed9e5ea47148
Revises: 001_initial
Create Date: 2026-06-10 21:38:09.459679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ed9e5ea47148'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contact_unlocks_seeker', table_name='contact_unlocks')
    op.add_column('listings', sa.Column('listing_type', sa.String(length=20), nullable=False, server_default="room_available"))
    op.drop_index('idx_listings_active', table_name='listings')
    op.drop_index('idx_listings_area', table_name='listings')
    op.drop_index('idx_listings_boosted', table_name='listings')
    op.drop_index('idx_listings_city', table_name='listings')
    op.drop_index('idx_listings_owner', table_name='listings')
    op.drop_index('idx_listings_property_type', table_name='listings')
    op.drop_index('idx_listings_rent', table_name='listings')
    op.drop_index('idx_otp_phone', table_name='otp_codes')
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.drop_index('idx_saved_listings_user', table_name='saved_listings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_saved_listings_user', 'saved_listings', ['user_id'], unique=False)
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.create_index('idx_otp_phone', 'otp_codes', ['phone'], unique=False)
    op.create_index('idx_listings_rent', 'listings', ['rent'], unique=False)
    op.create_index('idx_listings_property_type', 'listings', ['property_type'], unique=False)
    op.create_index('idx_listings_owner', 'listings', ['owner_id'], unique=False)
    op.create_index('idx_listings_city', 'listings', ['city'], unique=False)
    op.create_index('idx_listings_boosted', 'listings', ['is_boosted', 'boost_expires_at'], unique=False)
    op.create_index('idx_listings_area', 'listings', ['area'], unique=False)
    op.create_index('idx_listings_active', 'listings', ['is_active', 'expires_at'], unique=False)
    op.drop_column('listings', 'listing_type')
    op.create_index('idx_contact_unlocks_seeker', 'contact_unlocks', ['seeker_id'], unique=False)
    # ### end Alembic commands ###
